---
date-modified: 2025-08-23
---

\renewcommand{\Pr}[1]{\text{Pr}\left(#1\right)}
\renewcommand{\exp}[1]{\text{exp}\left\{#1\right\}}

# Preface

Statistical methods for networked systems are present in most disciplines. Despite language differences between areas, many methods developed to study specific problems can be helpful outside their original context; this is the premise of this book. **Applied Network Science with R** provides examples using the R programming language to study networked systems. Although most cases deal with social network analysis, the methods presented here can be applied to contexts such as biological networks, transportation networks, and many others.

::: {.callout-note}
## Spanish Version Available
A Spanish translation of this book is available at [es/](es/). The Spanish version was created using AI translation and may require human review for technical accuracy.
:::

The entire book was written using [quarto](https://quarto.org){target="_blank"}--a [literate programming](https://en.wikipedia.org/w/index.php?title=Literate_programming&oldid=1219921237) system that allows mixing text and code--meaning that all the code presented is 100% executable and, thus, reproducible. The source code is available on GitHub at [https://github.com/gvegayon/appliedsnar](https://github.com/gvegayon/appliedsnar){target="_blank"}. Readers are encouraged to download the code and execute it on their machines using either [RStudio](https://posit.co) or [VScode](https://code.visualstudio.com/).

Besides the R programming, we will be using <a href="https://posit.co" target="_blank">RStudio</a>. For data management, we will use <a href="https://cran.r-project.org/package=dplyr" target="_blank">`dplyr`</a> and <a href="https://cran.r-project.org/package=data.table" target="_blank">`data.table`</a>. The network data management and visualization packages we will use are  <a href="https://cran.r-project.org/package=igraph" target="_blank">`igraph`</a>, <a href="https://cran.r-project.org/package=netdiffuseR" target="_blank">netdiffuseR</a>, the <a href="https://statnet.org" target="_blank">statnet</a> suite, and <a href="https://cran.r-project.org/package=netplot" target="_blank">`netplot`</a>.

## About the project

This project began over six years ago as a part of a series of workshops and tutorials I ran at USC's <a href="https://cana.usc.edu" target="_blank">**Center for Applied Network Analysis**</a>. Today, I use it to gather and study statistical methods to analyze networks, emphasizing social and biological systems. Moreover, the book will use statistical computing methods as a core component.

## About the Author

I am a Research Assistant Professor at the <a href="https://medicine.utah.edu/internal-medicine/epidemiology" target="_blank">**University of Utah's Division of Epidemiology**</a>, where I work on studying Complex Systems using Statistical Computing. I was born and raised in Chile. I have over ten years of experience <a href="https://github.com/gvegayon" target="_blank">developing scientific software</a> focusing on high-performance computing, data visualization, and social network analysis. My training is in Public Policy (M.A. <a href="https://uai.cl" target="_blank">UAI</a>, 2011), Economics (M.Sc. <a href="https://caltech.edu" target="_blank">Caltech</a>, 2015), and Biostatistics (Ph.D. <a href="https://usc.edu" target="_blank">USC</a>, 2020).

I obtained my Ph.D. in Biostatistics under the supervision of <a href="https://scholar.google.com/citations?user=Zj5ky5gAAAAJ&hl=en" target="_blank">**Prof. Paul Marjoram**</a> and <a href="https://kayladelahaye.net/" target="_blank">**Prof. Kayla de la Haye**</a>, with my dissertation titled "*Essays on Bioinformatics and Social Network Analysis: Statistical and Computational Methods for Complex Systems.*"

If you'd like to learn more about me, please visit my website at <a href="https://ggvy.cl" target="_blank">https://ggvy.cl</a>.

## AI Disclosure

Starting in mid-2023, I have been using AI to help me write this book. Mainly, I use a combination of [GitHub co-pilot](https://github.com/features/copilot){target="_blank"}, which aids with code and text, and [Grammarly](https://grammarly.com){target="_blank"}, which aids with grammar and style. AI's role has been to help me write faster and more accurately, but it has not been involved in the book's conceptualization or the development of the methods presented here.
