# Applications {-}

# Introduction

```{r include=FALSE, cache=FALSE}
rm(list = ls())

pkgs <- c("igraph", "statnet", "sns", "network", "dplyr", "stringr",
          "tidyr", "tidyselect", "ergm", "netdiffuseR", "lattice", "RSiena",
          "magrittr", "netplot")
pkgs <- paste0("package:", pkgs)

for (pkg in pkgs)
  tryCatch(
    detach(pkg, unload = TRUE, character.only = TRUE, force = TRUE),
    error = function(e) e)
```

Social Network Analysis and Network Science, have a long scholarly tradition.
From social diffusion models to protein-interaction networks, these complex systems disciplines cover a wide range of problems across scientific fields. Yet, although these could be seen as wildly different, the object under the microscope is the same, networks. 

With a long history (and insufficient levels of inter-discipline collaboration, if you allow me to say) of scientific advances happing in a somewhat isolated fashion, the potential for cross-pollination between disciplines within network science is immense.

This book is an attempt to compile the many methods available in the realm of complexity sciences, provide an in-depth mathematical examination--when possible--, and provide a few examples illustrating their usage. 

