FROM rocker/tidyverse:4.5.1

RUN install2.r --error languageserver && \
    installGithub.r nx10/httpgd

# Installing the R package spatialreg
RUN apt-get update && apt-get install --no-install-recommends \
	-y libudunits2-dev libproj-dev libgdal-dev
RUN install2.r spatialreg

# Missing libraries
RUN apt-get install --no-install-recommends -y libglpk-dev

# Installing quarto
RUN quarto install tool tinytex --log-level warning

ENV PATH="/root/.TinyTeX/bin/x86_64-linux:${PATH}"

RUN install2.r --error -n 4 \
	igraph \
	netplot \
	netdiffuseR \
	Matrix \
	sna \
	network \
	ergm \
	intergraph \
	texreg \
	readstata13 \
	gridExtra \
	rgexf \
	microbenchmark \
	RSiena

CMD ["bash"]
