<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Applied SNA with R</title>
  <meta name="description" content="An improvised book on applied Social Network Analysis with R, this is(will be) a compilation of the materials presented in this series of workshop hosted by USC’s Center for Applied Network Analysis (CANA)">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="Applied SNA with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An improvised book on applied Social Network Analysis with R, this is(will be) a compilation of the materials presented in this series of workshop hosted by USC’s Center for Applied Network Analysis (CANA)" />
  <meta name="github-repo" content="USCCANA/appliedsnar" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Applied SNA with R" />
  
  <meta name="twitter:description" content="An improvised book on applied Social Network Analysis with R, this is(will be) a compilation of the materials presented in this series of workshop hosted by USC’s Center for Applied Network Analysis (CANA)" />
  

<meta name="author" content="George G. Vega Yon">


<meta name="date" content="2018-01-22">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="r-basics.html">
<link rel="next" href="applications.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied SNA with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>3</b> R Basics</a><ul>
<li class="chapter" data-level="3.1" data-path="r-basics.html"><a href="r-basics.html#what-is-r"><i class="fa fa-check"></i><b>3.1</b> What is R</a></li>
<li class="chapter" data-level="3.2" data-path="r-basics.html"><a href="r-basics.html#how-to-install-packages"><i class="fa fa-check"></i><b>3.2</b> How to install packages</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-1-sns-study.html"><a href="week-1-sns-study.html"><i class="fa fa-check"></i><b>4</b> Week 1: SNS Study</a><ul>
<li class="chapter" data-level="4.1" data-path="week-1-sns-study.html"><a href="week-1-sns-study.html#the-social-network-study"><i class="fa fa-check"></i><b>4.1</b> The Social Network Study</a></li>
<li class="chapter" data-level="4.2" data-path="week-1-sns-study.html"><a href="week-1-sns-study.html#reading-and-cleaning-the-data"><i class="fa fa-check"></i><b>4.2</b> Reading and <em>cleaning</em> the data</a></li>
<li class="chapter" data-level="4.3" data-path="week-1-sns-study.html"><a href="week-1-sns-study.html#retrieving-the-network"><i class="fa fa-check"></i><b>4.3</b> Retrieving the network</a></li>
<li class="chapter" data-level="4.4" data-path="week-1-sns-study.html"><a href="week-1-sns-study.html#plotting-the-network-in-igraph"><i class="fa fa-check"></i><b>4.4</b> Plotting the network in igraph</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>5</b> Applications</a><ul>
<li class="chapter" data-level="5.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>5.1</b> Example one</a></li>
<li class="chapter" data-level="5.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>5.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>6</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied SNA with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-1-sns-study" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Week 1: SNS Study</h1>
<div id="the-social-network-study" class="section level2">
<h2><span class="header-section-number">4.1</span> The Social Network Study</h2>
</div>
<div id="reading-and-cleaning-the-data" class="section level2">
<h2><span class="header-section-number">4.2</span> Reading and <em>cleaning</em> the data</h2>
<p>R has several ways of reading data in. You data can be Raw plain files like CSV, tab delimited or specified by column width, for which you can use the <a href="https://cran.r-project.org/package=readr"><code>readr</code></a> package; or it can be binary files like dta (Stata), Octave, SPSS, for which <a href="https://cran.r-project.org/package=readr"><code>foreign</code></a> can be used; or it could be excel files in which case you should be using <a href="https://cran.r-project.org/package=readxl"><code>readxl</code></a>. In our case, the data for this session is in Stata13 format, and so we will be using <a href="https://cran.r-project.org/package=readstata13"><code>readstata13</code></a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(magrittr)
<span class="kw">library</span>(readstata13)

<span class="co"># Reading the data</span>
dat &lt;-<span class="st"> </span><span class="kw">read.dta13</span>(<span class="st">&quot;SNS datamerged081315edited.dta&quot;</span>)

<span class="co"># Taking a look at the file</span>
<span class="kw">head</span>(dat[,<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>])</code></pre></div>
<pre><code>##   t4_SubjectID School photoid sch_friend41 sch_friend42
## 1    411104010    111       1          347          420
## 2    411103015    111       2          424          205
## 3    411603020    111       7           NA          505
## 4    411103026    111      13          608          387
## 5    411103016    111      14           NA           NA
## 6    411502003    111      15           NA          265</code></pre>
<p>For now, we won’t be using all ~2,000 columns of this data (which is mostly because we have a wide format dataset here), so we need to filter all this data. In order to do so, we can use the <code>select</code> function from the <code>dplyr</code> package</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_filtered &lt;-<span class="st"> </span><span class="kw">select</span>(
  dat,
  School, photoid,
  <span class="kw">matches</span>(<span class="st">&quot;^sch_friend.+&quot;</span>)
  )</code></pre></div>
<p>The function <code>matches</code> allows us using regular expressions to select variables (reguwhat!?). Regular expressions are, as I once overheard, <em>the poor man’s RA</em>. In this case, instead of us having to look for all the variables that start with the pattern <code>sch_friend</code>, we use regular expressions to catch that, character by character, we have:</p>
<ul>
<li><code>^</code>: Line start</li>
<li><code>sch_friend</code>: Followed by <code>sch_friend</code></li>
<li><code>.+</code>: Followed by anything not null.</li>
</ul>
<p>We will see more of this in the future. Now, if you don’t want to use <code>dplyr</code> to do this simple variable selection, you can always use the base R function <code>subset</code>. The following example is equivalent to what we just did using <code>dplyr::select</code>, although it can be slower<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_filtered &lt;-<span class="st"> </span><span class="kw">subset</span>(
  dat,
  <span class="dt">select =</span> <span class="kw">c</span>(
    <span class="st">&quot;School&quot;</span>, <span class="st">&quot;photoid&quot;</span>,
    <span class="kw">colnames</span>(dat)[<span class="kw">grepl</span>(<span class="st">&quot;sch_friend.+&quot;</span>, <span class="kw">colnames</span>(dat))]
    )
  )</code></pre></div>
<p>As you can see, the <code>dplyr</code> syntax is more clear.</p>
<p>Now suppose that we want to create a unique id using the school and photo id. In this case, since both variables are numeric, a good way of doing it is to encode the id such that, for example, the last three <code>x</code> numbers are the photoid and the first ones are the school id. To do this we need to take into account the range of the variables. Here, <code>photoid</code> has the following range:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(photo_id_ran &lt;-<span class="st"> </span><span class="kw">range</span>(dat_filtered<span class="op">$</span>photoid))</code></pre></div>
<pre><code>## [1]    1 2074</code></pre>
<p>As the variable spans up to 2074, we need to set the last 4 units of the variable to store the <code>photoid</code>. Again, we use <code>dplyr</code> to create this variable, and we will call it… <code>id</code> (mind blowing, right?):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(dat_filtered <span class="op">%&lt;&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">id =</span> School<span class="op">*</span><span class="dv">10000</span> <span class="op">+</span><span class="st"> </span>photoid)) <span class="op">%&gt;%</span>
<span class="st">  </span>head <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(School, photoid, id)</code></pre></div>
<pre><code>##   School photoid      id
## 1    111       1 1110001
## 2    111       2 1110002
## 3    111       7 1110007
## 4    111      13 1110013
## 5    111      14 1110014
## 6    111      15 1110015</code></pre>
<p>Wow, what happend in the last three lines of code! What is that <code>%&gt;%</code>? Well, that’s the <a href="http://r4ds.had.co.nz/pipes.html">piping operator</a>, and it is a very nice way of writing nested function calls. In this case, instead of having write something like</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_filtered<span class="op">$</span>id &lt;-<span class="st"> </span>dat_filtered<span class="op">$</span>School<span class="op">*</span><span class="dv">10000</span> <span class="op">+</span><span class="st"> </span>dat_filtered<span class="op">$</span>photoid
<span class="kw">subset</span>(<span class="kw">head</span>(dat_filtered), <span class="dt">select =</span> <span class="kw">c</span>(School, photoid, id))</code></pre></div>
</div>
<div id="retrieving-the-network" class="section level2">
<h2><span class="header-section-number">4.3</span> Retrieving the network</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyr)
<span class="kw">library</span>(stringr)</code></pre></div>
<p>Optionally, we can use the <code>tibble</code> type of object which is an alternative to the actual <code>data.frame</code>. This object is claimed to provide <em>more efficient methods for matrices and data frames</em>. We will use it for this bit.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_filtered &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(dat_filtered)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Maybe too much piping... but its cool!</span>
net &lt;-<span class="st"> </span>dat_filtered <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(id, School, <span class="kw">starts_with</span>(<span class="st">&quot;sch_friend&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> <span class="st">&quot;varname&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;content&quot;</span>, <span class="op">-</span>id, <span class="op">-</span>School) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(content)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(
    <span class="dt">friendid =</span> School<span class="op">*</span><span class="dv">10000</span> <span class="op">+</span><span class="st"> </span>content,
    <span class="dt">year     =</span> <span class="kw">str_extract</span>(varname, <span class="st">&quot;(?&lt;=[a-z])[0-9]&quot;</span>),
    <span class="dt">nnom     =</span> <span class="kw">str_extract</span>(varname, <span class="st">&quot;(?&lt;=[a-z][0-9])[0-9]+&quot;</span>)
  )</code></pre></div>
<p>Let’s take a look at this step by step:</p>
<ol style="list-style-type: decimal">
<li><p>First, we subset the data: We want to keep <code>id, School, sch_friend*</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_filtered <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(id, School, <span class="kw">starts_with</span>(<span class="st">&quot;sch_friend&quot;</span>))</code></pre></div>
<pre><code>## # A tibble: 2,164 x 78
##         id School sch_f… sch_f… sch_f… sch_… sch_… sch_… sch_… sch_… sch_…
##      &lt;dbl&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1 1110001    111    347    420    442   257    NA    NA    NA    NA    NA
##  2 1110002    111    424    205    536    NA    36    NA    NA    NA    NA
##  3 1110007    111     NA    505     NA    NA    NA    NA    NA    NA    NA
##  4 1110013    111    608    387     93   119   627   610   569    NA    NA
##  5 1110014    111     NA     NA    599    NA   134    NA   377    41   233
##  6 1110015    111     NA    265     NA   313   339    NA    NA    NA    NA
##  7 1110020    111     79    214    440    NA    NA    NA    NA   188   278
##  8 1110022    111     37    258     71   143   427   470   371    NA    NA
##  9 1110025    111     NA    185     NA    NA    NA    NA    NA    NA    NA
## 10 1110027    111     95    166    248   330   346    NA    NA    NA    NA
## # ... with 2,154 more rows, and 67 more variables: sch_friend410 &lt;int&gt;,
## #   sch_friend411 &lt;int&gt;, sch_friend412 &lt;int&gt;, sch_friend413 &lt;int&gt;,
## #   sch_friend414 &lt;int&gt;, sch_friend415 &lt;int&gt;, sch_friend416 &lt;int&gt;,
## #   sch_friend417 &lt;int&gt;, sch_friend418 &lt;int&gt;, sch_friend419 &lt;int&gt;,
## #   sch_friend31 &lt;int&gt;, sch_friend32 &lt;int&gt;, sch_friend33 &lt;int&gt;,
## #   sch_friend34 &lt;int&gt;, sch_friend35 &lt;int&gt;, sch_friend36 &lt;int&gt;,
## #   sch_friend37 &lt;int&gt;, sch_friend38 &lt;int&gt;, sch_friend39 &lt;int&gt;,
## #   sch_friend310 &lt;int&gt;, sch_friend311 &lt;int&gt;, sch_friend312 &lt;int&gt;,
## #   sch_friend313 &lt;int&gt;, sch_friend314 &lt;int&gt;, sch_friend315 &lt;int&gt;,
## #   sch_friend316 &lt;int&gt;, sch_friend317 &lt;int&gt;, sch_friend318 &lt;int&gt;,
## #   sch_friend319 &lt;int&gt;, sch_friend11 &lt;int&gt;, sch_friend12 &lt;int&gt;,
## #   sch_friend13 &lt;int&gt;, sch_friend14 &lt;int&gt;, sch_friend15 &lt;int&gt;,
## #   sch_friend16 &lt;int&gt;, sch_friend17 &lt;int&gt;, sch_friend18 &lt;int&gt;,
## #   sch_friend19 &lt;int&gt;, sch_friend110 &lt;int&gt;, sch_friend111 &lt;int&gt;,
## #   sch_friend112 &lt;int&gt;, sch_friend113 &lt;int&gt;, sch_friend114 &lt;int&gt;,
## #   sch_friend115 &lt;int&gt;, sch_friend116 &lt;int&gt;, sch_friend117 &lt;int&gt;,
## #   sch_friend118 &lt;int&gt;, sch_friend119 &lt;int&gt;, sch_friend21 &lt;int&gt;,
## #   sch_friend22 &lt;int&gt;, sch_friend23 &lt;int&gt;, sch_friend24 &lt;int&gt;,
## #   sch_friend25 &lt;int&gt;, sch_friend26 &lt;int&gt;, sch_friend27 &lt;int&gt;,
## #   sch_friend28 &lt;int&gt;, sch_friend29 &lt;int&gt;, sch_friend210 &lt;int&gt;,
## #   sch_friend211 &lt;int&gt;, sch_friend212 &lt;int&gt;, sch_friend213 &lt;int&gt;,
## #   sch_friend214 &lt;int&gt;, sch_friend215 &lt;int&gt;, sch_friend216 &lt;int&gt;,
## #   sch_friend217 &lt;int&gt;, sch_friend218 &lt;int&gt;, sch_friend219 &lt;int&gt;</code></pre></li>
<li><p>Then, we reshape it to <em>long</em> format: By transposing all the <code>sch_friend*</code> to long</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_filtered <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(id, School, <span class="kw">starts_with</span>(<span class="st">&quot;sch_friend&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> <span class="st">&quot;varname&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;content&quot;</span>, <span class="op">-</span>id, <span class="op">-</span>School)</code></pre></div>
<pre><code>## # A tibble: 164,464 x 4
##         id School varname      content
##      &lt;dbl&gt;  &lt;int&gt; &lt;chr&gt;          &lt;int&gt;
##  1 1110001    111 sch_friend41     347
##  2 1110002    111 sch_friend41     424
##  3 1110007    111 sch_friend41      NA
##  4 1110013    111 sch_friend41     608
##  5 1110014    111 sch_friend41      NA
##  6 1110015    111 sch_friend41      NA
##  7 1110020    111 sch_friend41      79
##  8 1110022    111 sch_friend41      37
##  9 1110025    111 sch_friend41      NA
## 10 1110027    111 sch_friend41      95
## # ... with 164,454 more rows</code></pre></li>
<li><p>We remove all the <code>NAs</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_filtered <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(id, School, <span class="kw">starts_with</span>(<span class="st">&quot;sch_friend&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> <span class="st">&quot;varname&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;content&quot;</span>, <span class="op">-</span>id, <span class="op">-</span>School) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(content))</code></pre></div>
<pre><code>## # A tibble: 39,561 x 4
##         id School varname      content
##      &lt;dbl&gt;  &lt;int&gt; &lt;chr&gt;          &lt;int&gt;
##  1 1110001    111 sch_friend41     347
##  2 1110002    111 sch_friend41     424
##  3 1110013    111 sch_friend41     608
##  4 1110020    111 sch_friend41      79
##  5 1110022    111 sch_friend41      37
##  6 1110027    111 sch_friend41      95
##  7 1110029    111 sch_friend41     190
##  8 1110030    111 sch_friend41      28
##  9 1110032    111 sch_friend41     484
## 10 1110035    111 sch_friend41     512
## # ... with 39,551 more rows</code></pre></li>
<li><p>And finally, we create three new variables from this dataset: <code>friendid</code>, <code>year</code>, and <code>nom_num</code> (nomination number). All this using regular expressions:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_filtered <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(id, School, <span class="kw">starts_with</span>(<span class="st">&quot;sch_friend&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> <span class="st">&quot;varname&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;content&quot;</span>, <span class="op">-</span>id, <span class="op">-</span>School) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(content)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(
    <span class="dt">friendid =</span> School<span class="op">*</span><span class="dv">10000</span> <span class="op">+</span><span class="st"> </span>content,
    <span class="dt">year     =</span> <span class="kw">str_extract</span>(varname, <span class="st">&quot;(?&lt;=[a-z])[0-9]&quot;</span>),
    <span class="dt">nnom     =</span> <span class="kw">str_extract</span>(varname, <span class="st">&quot;(?&lt;=[a-z][0-9])[0-9]+&quot;</span>)
    )</code></pre></div>
<pre><code>## # A tibble: 39,561 x 7
##         id School varname      content friendid year  nnom 
##      &lt;dbl&gt;  &lt;int&gt; &lt;chr&gt;          &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;
##  1 1110001    111 sch_friend41     347  1110347 4     1    
##  2 1110002    111 sch_friend41     424  1110424 4     1    
##  3 1110013    111 sch_friend41     608  1110608 4     1    
##  4 1110020    111 sch_friend41      79  1110079 4     1    
##  5 1110022    111 sch_friend41      37  1110037 4     1    
##  6 1110027    111 sch_friend41      95  1110095 4     1    
##  7 1110029    111 sch_friend41     190  1110190 4     1    
##  8 1110030    111 sch_friend41      28  1110028 4     1    
##  9 1110032    111 sch_friend41     484  1110484 4     1    
## 10 1110035    111 sch_friend41     512  1110512 4     1    
## # ... with 39,551 more rows</code></pre>
<p>The regular expression <code>(?&lt;=[a-z])</code> matches a string that is preceeded by any letter from <em>a</em> to <em>z</em>, whereas the expression <code>[0-9]</code> matches a single number. Hence, from the string <code>&quot;sch_friend12&quot;</code>, the regular expression will only match the <code>1</code>, as it is the only number followed by a letter. On the other hand, the expression <code>(?&lt;=[a-z][0-9])</code> matches a string that is preceeded by a letter from <em>a</em> to <em>z</em> and a number from <em>0</em> to <em>9</em>; and the expression <code>[0-9]+</code> matches a string of numbers–so it could be more than one. Hence, from the string <code>&quot;sch_friend12&quot;</code>, we will get <code>2</code>. We can actually se this</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str_extract</span>(<span class="st">&quot;sch_friend12&quot;</span>, <span class="st">&quot;(?&lt;=[a-z])[0-9]&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;1&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str_extract</span>(<span class="st">&quot;sch_friend12&quot;</span>, <span class="st">&quot;(?&lt;=[a-z][0-9])[0-9]+&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;2&quot;</code></pre></li>
</ol>
<p>Now that we have this edgelist, we can create an igraph object</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vertices &lt;-<span class="st"> </span>dat_filtered <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(id, School)</code></pre></div>
<p>Let’s now use the function <code>graph_from_data_frame</code> to create an <code>igraph</code> object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(igraph)

ig_year1 &lt;-<span class="st"> </span>net <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year <span class="op">==</span><span class="st"> &quot;1&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(id, friendid) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">graph_from_data_frame</span>(
    <span class="dt">vertices =</span> vertices
    )</code></pre></div>
<pre><code>## Error in graph_from_data_frame(., vertices = vertices): Some vertex names in edge list are not listed in vertex data frame</code></pre>
<p>Ups, it seems that individuals are making nominations to other students that were not included on the survery. How to solve that? Well, it all depends on what you need to do! In this case, we will go for the <em>quietly-remove-em’-and-don’t-tell</em> strategy:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ig_year1 &lt;-<span class="st"> </span>net <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(year <span class="op">==</span><span class="st"> &quot;1&quot;</span>, School <span class="op">==</span><span class="st"> </span><span class="dv">111</span>) <span class="op">%&gt;%</span>
<span class="st">  </span>
<span class="st">  </span><span class="co"># Extra line, all nominations must be in ego too.</span>
<span class="st">  </span><span class="kw">filter</span>(friendid <span class="op">%in%</span><span class="st"> </span>id) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span>
<span class="st">  </span><span class="kw">select</span>(id, friendid) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">graph_from_data_frame</span>(
    <span class="dt">vertices =</span> vertices
    )</code></pre></div>
</div>
<div id="plotting-the-network-in-igraph" class="section level2">
<h2><span class="header-section-number">4.4</span> Plotting the network in igraph</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(ig_year1)</code></pre></div>
<p><img src="appliedsnar_files/figure-html/03-plot-raw-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Creating a subgraph</span>
ig_year1_<span class="dv">111</span> &lt;-<span class="st"> </span><span class="kw">induced_subgraph</span>(
  ig_year1,
  <span class="kw">which</span>(<span class="kw">degree</span>(ig_year1) <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw">V</span>(ig_year1)<span class="op">$</span>School <span class="op">==</span><span class="st"> </span><span class="dv">111</span>)
)

<span class="co"># Getting colors</span>
cols &lt;-<span class="st"> </span><span class="kw">V</span>(ig_year1_<span class="dv">111</span>)<span class="op">$</span>School <span class="op">%&gt;%</span><span class="st"> </span>as.factor
cols &lt;-<span class="st"> </span><span class="kw">colors</span>()[cols]

<span class="co"># Fancy graph</span>
<span class="kw">set.seed</span>(<span class="dv">1</span>)
<span class="kw">plot</span>(
  ig_year1_<span class="dv">111</span>,
  <span class="dt">vertex.size     =</span> <span class="kw">degree</span>(ig_year1_<span class="dv">111</span>)<span class="op">/</span><span class="dv">4</span>,
  <span class="dt">vertex.label    =</span> <span class="ot">NA</span>,
  <span class="dt">edge.arrow.size =</span> .<span class="dv">25</span>,
  <span class="dt">vertex.color    =</span> cols,
  <span class="dt">layout          =</span> layout_with_fr
  )</code></pre></div>
<p><img src="appliedsnar_files/figure-html/03-plot-neat1-1.png" width="672" /></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>Besides of having nice syntax, <code>dplyr</code> offers optimized routines to handle your data. I personally use it specifically for that, as that can be nice when you are dealing with relatively large datasets.<a href="week-1-sns-study.html#fnref2">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="r-basics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="applications.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
